### ISSUE TITLE
Allow to change locale at runtime & store the last locale used on FS

### ISSUE THREAD

**Issue by dsferruzza** [makers-for-life/makair-control-ui#26]
This might be very important for the CE certification

**Comment by valeriansaliou** [comment]
**Steps:**

1. Ability to parse a save .data file located in a file path passed by an env var (be tolerant to failure/errors; if there is a read error just clear out the file and reset it)
2. If any locale is set in this file, and is supported by the UI, use it, otherwise fallback to locale (this, only if no locale is forced using an environment variable)
3. Lastly, build the locale switcher in the settings section (which writes the current locale to the .data file)

**Comment by valeriansaliou** [comment]
See: https://docs.rs/settingsfile/0.2.8/settingsfile/index.html
