### ISSUE TITLE
Inital value of the expiratory term setting

### ISSUE THREAD

**Issue by Benhalor** [makers-for-life/makair-control-ui#33]
At startup, the initial value of the expiratory term setting is displayed as 0.0
Pretty sure that this issue didnt exist some days ago

![image](https://user-images.githubusercontent.com/10956689/97118965-759a6b00-170d-11eb-8d08-b3c3a7fd22a2.png)

**Comment by valeriansaliou** [comment]
I've checked, and the machine_snapshot.cpm_command reported on a fresh recording from a live machine running firmware v3.x.x also reports this.

This value is being served from the telemetry library as-is, so I'm pretty sure the issue is not in the firmware. I'll replace any zero value w/ "n/a" to make it clear we did not receive yet any value from the motherboard.
